header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Krzysztof Karczewski
  paths:
    - '**/*.kt'
  paths-ignore:
    - '**/build/**'
    - '**/.gradle/**'
    - '**/.idea/**'
    - '**/iosApp/**'
  comment: on-failure
